module.exports = {
    ACCESS_TOKEN :"EAADwlFkaTB4BAP4lJtpirBL4byiEaMvmz6EVVNRgeerTx8WnMZBNy8mdOgMZBOe5ZA4KbSsCqjbSGlSo47ehTeya5quTh76rZCK9baZAjayNMYOEWrpQfNQfaYIeZCqUqR50QOrBNLDeIjYSjDfUvsE4B7VASFlu8HrOJbZBuC6rgZDZD",
    VERIFY_TOKEN : 'misalpavbro',
    PORT : 4005
}